### ISSUE TITLE
ADMT is failing with error below

### ISSUE THREAD

**Issue by arpijain1** [oracle/ansible-database-migration-tool#3]
TASK [target_restore_role : Download TDE file from OSS (non ExaCS)] *****************************************************************************************
 [WARNING]: Consider using the get_url or uri module rather than running 'curl'.  If you need to use command because get_url or uri is insufficient you can
add 'warn: false' to this command task or set 'command_warnings=False' in ansible.cfg to get rid of this message.

changed: [172.17.30.130]

TASK [target_restore_role : Unpack the source wallet on target TDE location (non ExaCS)] ********************************************************************
fatal: [172.17.30.130]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/opt/oracle/dcs/commonstore/wallets/tde/SNDBX12C_iad169/_tde.tgz\". Make sure the required command to extract the file is installed. Command \"/bin/gtar\" could not handle archive. Command \"/bin/unzip\" could not handle archive."}

PLAY RECAP **************************************************************************************************************************************************
172.17.30.130              : ok=19   changed=1    unreachable=0    failed=1    skipped=14   rescued=0    ignored=0

Both directory exist.

[oracle@sandbox12c bin]$ ls -lrt unzip
-rwxr-xr-x 2 root root 185576 Jun  9  2019 unzip
[oracle@sandbox12c bin]$ ls -lrt gtar
lrwxrwxrwx 1 root root 3 Jan 30  2020 gtar -> tar
[oracle@sandbox12c bin]$ exit

**Comment by arpijain1** [comment]
Backup is available in Object storage but while running restore it is erroring out.

**Comment by mlinxfeld** [comment]
@arpijain1 as we have discussed this problem was related to not fully supported configuration in your setup.json file. I am closing this issue.
